<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 17-12-5
 * Time: 上午10:42
 */

namespace app\common\model\wish;


use think\Model;

class WishWaitUploadProductInfo extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function product()
    {
        return $this->hasOne(WishWaitUploadProduct::class,'id','id');
    }
}