<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-5-22
 * Time: 下午2:34
 */

namespace app\common\model\shopee;


use think\Model;

class ShopeeCategory extends Model
{
    protected $autoWriteTimestamp=true;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function setHasChildrenAttr($v){
        if($v){
            return 1;
        }else{
            return 0;
        }
    }
    public static function categoryNameTree($category_id,&$name=''){
        $category = self::where('category_id',$category_id)->find();
        if($category){
            $name= $category['category_name'].">>".$name;
            self::categoryNameTree($category['parent_id'],$name);
        }
    }
}