<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-5-25
 * Time: 下午5:21
 */

namespace app\common\model\shopee;


use app\common\model\Goods;
use app\common\model\User;
use think\Model;

class  ShopeeProduct extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function setStatusAttr($v){
        if($v=='NORMAL'){
            return 1;
        }elseif($v=='DELETED'){
            return 2;
        }elseif($v=='BANNED'){
            return 3;
        }else if (in_array($v, [1,2,3])) {
            return $v;
        } else {
            return 0;
        }
    }

    public function setConditionAttr($v) {
        return $v=='USED' ? 1 : 0;
    }
    public function info(){
        return $this->hasOne(ShopeeProductInfo::class,'id','id');
    }
    public function variants(){
        return $this->hasMany(ShopeeVariant::class,'pid','id');
    }
    public function account(){
        return $this->hasOne(ShopeeAccount::class,'id','account_id');

    }
    public function user(){
        return $this->hasOne(User::class,'id','create_id');

    }
    public function goods(){
        return $this->hasOne(Goods::class,'id','goods_id');
    }
    public function sellerName($create_id){
        $user =  User::where('id',$create_id)->find();
        $sellName=$user?$user->realname:'';
        return $sellName;
    }
}