<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-5-29
 * Time: 下午2:03
 */

namespace app\common\model\shopee;


use think\Model;

class ShopeeDiscount extends Model
{
    protected $autoWriteTimestamp = true;
    const STATUS=[
        0=>'ALL',
        1=>'UPCOMING',
        2=>'ONGOING',
        3=>'EXPIRED',
    ];
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public static function saveData($data){
        (new self())->allowField(true)->save($data);
    }
    public function account($account_id){
        $account =  ShopeeAccount::where('id',$account_id)->find();
        $code = '';
        if($account){
            $code = $account['code'];
        }
        return $code;
    }
}