<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-5-28
 * Time: 下午5:59
 */

namespace app\common\model\shopee;


use app\common\model\User;
use think\Model;

class ShopeeActionLog extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function product(){
        return $this->hasOne(ShopeeProduct::class,'item_id','product_id');
    }
    public function user(){
        return $this->hasOne(User::class,'id','create_id');
    }
    public function getNewDataAttr($v){
        return json_decode($v,true);
    }
    public function getOldDataAttr($v){
        return json_decode($v,true);
    }
}