<?php

namespace app\common\model;

use think\Model;

/**
 * Created by PhpStorm.
 * User: PHILL
 * Date: 2016/11/4
 * Time: 17:10
 */
class GoodsSku extends Model
{
    protected $autoWriteTimestamp = true;

    /**
     * 初始化数据
     */
    protected function initialize()
    {
        //需要调用 mdoel 的 initialize 方法
        parent::initialize();
    }

    public function image()
    {
        return $this->hasOne(GoodsGallery::class, 'sku_id', 'id');
    }

    public function getFields()
    {
        return parent::getTableFields(['table' => $this->table]); // TODO: Change the autogenerated stub
    }


}