<?php
/**
 * Created by PhpStorm.
 * User: rondaful_user
 * Date: 2019/2/10
 * Time: 9:56
 */

namespace app\common\model;


use app\common\service\Common;
use erp\ErpModel;

class AutoCompleteModel extends ErpModel
{
    protected $autoWriteTimestamp = true;//自动写入时间戳
    protected $createId = 'create_id';//创建人id字段名
    protected $updateId = 'update_id';//更新人id字段名

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $userInfo = Common::getUserInfo();
        $userId = $userInfo['user_id'] ?? 0;

        //注册插入事件，自动填充创建人id
        if ($this->createId) {
            $createId = $this->createId;
            static::event('before_insert', function ($model) use ($userId,$createId) {
                if (!isset($model[$createId])) {
                    $model->$createId = $userId;
                }
            });
        }
        //注册更新事件，自动填充更新人id
        if ($this->updateId) {
            $updateId = $this->updateId;
            static::event('before_update', function ($model) use ($userId,$updateId) {
                if (!isset($model[$updateId])) {
                    $model->$updateId = $userId;
                }
            });
        }
    }

    protected static function init()
    {
        parent::init();
    }


}