<?php
namespace app\common\model;
use app\warehouse\service\PackageReturnService;
use think\Model;

/**
 * Created by PhpStorm.
 * User: phill
 * Date: 2017/12/7
 * Time: 20:20
 */
class PackageReturnLog extends Model
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /** 状态进度
     * @param $value
     * @return int
     */
    public function getProcessAttr($value)
    {
        $packageReturnService = new PackageReturnService();
        $process = $packageReturnService->getStatusName(false,$value);
        return $process['label'] ?? '';
    }
}