<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-8-2
 * Time: 下午1:37
 */

namespace app\common\model;


use think\Model;

class Progress extends Model
{
    protected $createTime = 'create_time';
    // 更新时间字段
    protected $updateTime = 'update_time';
    protected $autoWriteTimestamp = true;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function username($id){
        $user =  User::where('id',$id)->find();
        if($user){
            return $user->realname;
        }else{
            return '';
        }
    }
}