<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-5-30
 * Time: 下午6:57
 */

namespace app\common\model\shopee;


use think\Model;

class ShopeeLogistic extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}