<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Zend\\Validator\\' => array($vendorDir . '/zendframework/zend-validator/src'),
    'Zend\\Uri\\' => array($vendorDir . '/zendframework/zend-uri/src'),
    'Zend\\Stdlib\\' => array($vendorDir . '/zendframework/zend-stdlib/src'),
    'Zend\\Soap\\' => array($vendorDir . '/zendframework/zend-soap/src'),
    'Zend\\ServiceManager\\' => array($vendorDir . '/zendframework/zend-servicemanager/src'),
    'Zend\\Server\\' => array($vendorDir . '/zendframework/zend-server/src'),
    'Zend\\Log\\' => array($vendorDir . '/zendframework/zend-log/src'),
    'Zend\\Loader\\' => array($vendorDir . '/zendframework/zend-loader/src'),
    'Zend\\Http\\' => array($vendorDir . '/zendframework/zend-http/src'),
    'Zend\\EventManager\\' => array($vendorDir . '/zendframework/zend-eventmanager/src'),
    'Zend\\Escaper\\' => array($vendorDir . '/zendframework/zend-escaper/src'),
    'Zend\\Db\\' => array($vendorDir . '/zendframework/zend-db/src'),
    'Zend\\Config\\' => array($vendorDir . '/zendframework/zend-config/src'),
    'Zend\\Code\\' => array($vendorDir . '/zendframework/zend-code/src'),
    'Zend\\Authentication\\' => array($vendorDir . '/zendframework/zend-authentication/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Interop\\Container\\' => array($vendorDir . '/container-interop/container-interop/src/Interop/Container'),
);
