<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-3-5
 * Time: 下午5:48
 */

namespace app\common\model;


use think\Model;

class PublishCollect extends Model
{
    protected $autoWriteTimestamp=true;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}