<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-5-25
 * Time: 下午5:22
 */

namespace app\common\model\shopee;


use think\Model;

class ShopeeVariant extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function setStatusAttr($v){
        if($v=='MODEL_NORMAL'){
            return 1;
        }else{
            return 0;
        }
    }
    public function product(){
        return $this->hasOne(ShopeeProduct::class,'id','pid');
    }
}