<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-5-23
 * Time: 下午3:08
 */

namespace app\common\model\wish;


use think\Model;

class WishShippableCountries extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}