<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'be84b43c07c8beae9f4053ce7edcc585' => $baseDir . '/sdk/autoload.php',
);
