<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 17-12-7
 * Time: 下午4:47
 */

namespace app\common\model\aliexpress;


use think\Model;

class AliexpressRsyncListingLog extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}