<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 17-10-30
 * Time: 下午2:33
 */

namespace app\common\model\aliexpress;

use think\Model;
class AliexpressPublishTemplateLog extends Model
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}