<?php
/**
 * AddPackageWithoutServiceResponsesData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eBay国际物流平台商户接口
 *
 * eBay国际物流平台商户接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * AddPackageWithoutServiceResponsesData Class Doc Comment
 *
 * @category Class
 * @description åè£¹è¿ååæ°
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddPackageWithoutServiceResponsesData implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AddPackageWithoutServiceResponsesData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'unavailable_service_list' => '\Swagger\Client\Model\UnavailableServiceResponses[]',
        'available_service_list' => '\Swagger\Client\Model\AvailableServiceResponses[]',
        'package_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'unavailable_service_list' => null,
        'available_service_list' => null,
        'package_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'unavailable_service_list' => 'unavailableServiceList',
        'available_service_list' => 'availableServiceList',
        'package_id' => 'packageId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'unavailable_service_list' => 'setUnavailableServiceList',
        'available_service_list' => 'setAvailableServiceList',
        'package_id' => 'setPackageId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'unavailable_service_list' => 'getUnavailableServiceList',
        'available_service_list' => 'getAvailableServiceList',
        'package_id' => 'getPackageId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['unavailable_service_list'] = isset($data['unavailable_service_list']) ? $data['unavailable_service_list'] : null;
        $this->container['available_service_list'] = isset($data['available_service_list']) ? $data['available_service_list'] : null;
        $this->container['package_id'] = isset($data['package_id']) ? $data['package_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['unavailable_service_list'] === null) {
            $invalidProperties[] = "'unavailable_service_list' can't be null";
        }
        if ($this->container['available_service_list'] === null) {
            $invalidProperties[] = "'available_service_list' can't be null";
        }
        if ($this->container['package_id'] === null) {
            $invalidProperties[] = "'package_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['unavailable_service_list'] === null) {
            return false;
        }
        if ($this->container['available_service_list'] === null) {
            return false;
        }
        if ($this->container['package_id'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets unavailable_service_list
     *
     * @return \Swagger\Client\Model\UnavailableServiceResponses[]
     */
    public function getUnavailableServiceList()
    {
        return $this->container['unavailable_service_list'];
    }

    /**
     * Sets unavailable_service_list
     *
     * @param \Swagger\Client\Model\UnavailableServiceResponses[] $unavailable_service_list ä¸å¯ç¨ç©æµæå¡(1.5çæ¬)
     *
     * @return $this
     */
    public function setUnavailableServiceList($unavailable_service_list)
    {
        $this->container['unavailable_service_list'] = $unavailable_service_list;

        return $this;
    }

    /**
     * Gets available_service_list
     *
     * @return \Swagger\Client\Model\AvailableServiceResponses[]
     */
    public function getAvailableServiceList()
    {
        return $this->container['available_service_list'];
    }

    /**
     * Sets available_service_list
     *
     * @param \Swagger\Client\Model\AvailableServiceResponses[] $available_service_list å¯ç¨ç©æµæå¡
     *
     * @return $this
     */
    public function setAvailableServiceList($available_service_list)
    {
        $this->container['available_service_list'] = $available_service_list;

        return $this;
    }

    /**
     * Gets package_id
     *
     * @return string
     */
    public function getPackageId()
    {
        return $this->container['package_id'];
    }

    /**
     * Sets package_id
     *
     * @param string $package_id åè£¹ID
     *
     * @return $this
     */
    public function setPackageId($package_id)
    {
        $this->container['package_id'] = $package_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


