<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-6-15
 * Time: 下午3:13
 */

namespace app\common\model\aliexpress;


use think\Model;

class AliexpressAccountPhotobank extends Model
{
    protected $autoWriteTimestamp = true;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}