<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 17-11-14
 * Time: 下午4:47
 */

namespace app\common\model\aliexpress;


use think\Model;

class AliexpressQuoteCountry extends Model
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}