# SwaggerClient-php
eBay国际物流平台商户接口

This PHP package is automatically generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project:

- API version: 1.0.0
- Build package: io.swagger.codegen.languages.PhpClientCodegen

## Requirements

PHP 5.5 and later

## Installation & Usage
### Composer

To install the bindings via [Composer](http://getcomposer.org/), add the following to `composer.json`:

```
{
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com//.git"
    }
  ],
  "require": {
    "/": "*@dev"
  }
}
```

Then run `composer install`

### Manual Installation

Download the files and include `autoload.php`:

```php
    require_once('/path/to/SwaggerClient-php/vendor/autoload.php');
```

## Tests

To run the unit tests:

```
composer install
./vendor/bin/phpunit
```

## Getting Started

Please follow the [installation procedure](#installation--usage) and then run the following:

```php
<?php
require_once(__DIR__ . '/vendor/autoload.php');

$apiInstance = new Swagger\Client\Api\OpenApiApi(
    // If you want use custom http client, pass your client which implements `GuzzleHttp\ClientInterface`.
    // This is optional, `GuzzleHttp\Client` will be used as default.
    new GuzzleHttp\Client()
);
$authorization = "authorization_example"; // string | 调用登录认证接口取得的token值
$add_address_preference_request = new \Swagger\Client\Model\AddAddressPreferenceRequest(); // \Swagger\Client\Model\AddAddressPreferenceRequest | addAddressPreferenceRequest

try {
    $result = $apiInstance->addAddressPreference($authorization, $add_address_preference_request);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling OpenApiApi->addAddressPreference: ', $e->getMessage(), PHP_EOL;
}

?>
```

## Documentation for API Endpoints

All URIs are relative to *https://open.edisebay.com*

Class | Method | HTTP request | Description
------------ | ------------- | ------------- | -------------
*OpenApiApi* | [**addAddressPreference**](docs/Api/OpenApiApi.md#addaddresspreference) | **POST** /v1/api/AddAddressPreference | 新增地址信息
*OpenApiApi* | [**addConsignPreference**](docs/Api/OpenApiApi.md#addconsignpreference) | **POST** /v1/api/AddConsignPreference | 新增交运偏好
*OpenApiApi* | [**addPackage**](docs/Api/OpenApiApi.md#addpackage) | **POST** /v1/api/AddPackage | 指定物流服务上传包裹
*OpenApiApi* | [**addPackageWithoutService**](docs/Api/OpenApiApi.md#addpackagewithoutservice) | **POST** /v1/api/AddPackageWithoutService | 无指定物流服务上传包裹
*OpenApiApi* | [**assignService**](docs/Api/OpenApiApi.md#assignservice) | **POST** /v1/api/AssignService | 指定包裹物流服务
*OpenApiApi* | [**cancelPackages**](docs/Api/OpenApiApi.md#cancelpackages) | **POST** /v1/api/CancelPackages | 取消包裹信息
*OpenApiApi* | [**confirmPackages**](docs/Api/OpenApiApi.md#confirmpackages) | **POST** /v1/api/ConfirmPackages | 确认并交运包裹信息
*OpenApiApi* | [**deletePackages**](docs/Api/OpenApiApi.md#deletepackages) | **POST** /v1/api/DeletePackages | 删除包裹信息
*OpenApiApi* | [**fetchToken**](docs/Api/OpenApiApi.md#fetchtoken) | **POST** /v1/api/FetchToken | 登录认证
*OpenApiApi* | [**getActualCost**](docs/Api/OpenApiApi.md#getactualcost) | **POST** /v1/api/GetActualCost | 获取包裹实际运费
*OpenApiApi* | [**getAddressPreferenceList**](docs/Api/OpenApiApi.md#getaddresspreferencelist) | **POST** /v1/api/GetAddressPreferenceList | 获取地址信息列表
*OpenApiApi* | [**getConsignPreferenceList**](docs/Api/OpenApiApi.md#getconsignpreferencelist) | **POST** /v1/api/GetConsignPreferenceList | 获取交运偏好列表
*OpenApiApi* | [**getDropoffSiteList**](docs/Api/OpenApiApi.md#getdropoffsitelist) | **POST** /v1/api/GetDropoffSiteList | 获取自送站点列表
*OpenApiApi* | [**getHandoverSheet**](docs/Api/OpenApiApi.md#gethandoversheet) | **POST** /v1/api/GetHandoverSheet | 获取交接单打印详情
*OpenApiApi* | [**getItemPackageId**](docs/Api/OpenApiApi.md#getitempackageid) | **POST** /v1/api/GetItemPackageId | 查询物品包裹ID
*OpenApiApi* | [**getLabel**](docs/Api/OpenApiApi.md#getlabel) | **POST** /v1/api/GetLabel | 获取面单打印详情
*OpenApiApi* | [**getPackageDetail**](docs/Api/OpenApiApi.md#getpackagedetail) | **POST** /v1/api/GetPackageDetail | 获取包裹详情
*OpenApiApi* | [**getPackageStatus**](docs/Api/OpenApiApi.md#getpackagestatus) | **POST** /v1/api/GetPackageStatus | 获取包裹状态
*OpenApiApi* | [**getServiceList**](docs/Api/OpenApiApi.md#getservicelist) | **POST** /v1/api/GetServiceList | 获取物流服务列表
*OpenApiApi* | [**getTrackingDetail**](docs/Api/OpenApiApi.md#gettrackingdetail) | **POST** /v1/api/GetTrackingDetail | 获取包裹物流跟踪信息
*OpenApiApi* | [**recreatePackage**](docs/Api/OpenApiApi.md#recreatepackage) | **POST** /v1/api/RecreatePackage | 重新发货
*OpenApiApi* | [**updateAddressPreference**](docs/Api/OpenApiApi.md#updateaddresspreference) | **POST** /v1/api/UpdateAddressPreference | 更新地址信息
*OpenApiApi* | [**updateConsignPreference**](docs/Api/OpenApiApi.md#updateconsignpreference) | **POST** /v1/api/UpdateConsignPreference | 更新交运偏好


## Documentation For Models

 - [AddAddressPreferenceRequest](docs/Model/AddAddressPreferenceRequest.md)
 - [AddAddressPreferenceRequestData](docs/Model/AddAddressPreferenceRequestData.md)
 - [AddAddressPreferenceResponses](docs/Model/AddAddressPreferenceResponses.md)
 - [AddAddressPreferenceResponsesData](docs/Model/AddAddressPreferenceResponsesData.md)
 - [AddConsignPreferenceRequest](docs/Model/AddConsignPreferenceRequest.md)
 - [AddConsignPreferenceRequestData](docs/Model/AddConsignPreferenceRequestData.md)
 - [AddConsignPreferenceResponses](docs/Model/AddConsignPreferenceResponses.md)
 - [AddConsignPreferenceResponsesData](docs/Model/AddConsignPreferenceResponsesData.md)
 - [AddPackageRequest](docs/Model/AddPackageRequest.md)
 - [AddPackageResponses](docs/Model/AddPackageResponses.md)
 - [AddPackageResponsesData](docs/Model/AddPackageResponsesData.md)
 - [AddPackageWithoutServiceRequest](docs/Model/AddPackageWithoutServiceRequest.md)
 - [AddPackageWithoutServiceResponses](docs/Model/AddPackageWithoutServiceResponses.md)
 - [AddPackageWithoutServiceResponsesData](docs/Model/AddPackageWithoutServiceResponsesData.md)
 - [AddressInfoResponses](docs/Model/AddressInfoResponses.md)
 - [AssignServiceRequest](docs/Model/AssignServiceRequest.md)
 - [AssignServiceRequestData](docs/Model/AssignServiceRequestData.md)
 - [AssignServiceResponses](docs/Model/AssignServiceResponses.md)
 - [AssignServiceResponsesData](docs/Model/AssignServiceResponsesData.md)
 - [AvailableServiceResponses](docs/Model/AvailableServiceResponses.md)
 - [CancelPackagesRequest](docs/Model/CancelPackagesRequest.md)
 - [CancelPackagesRequestData](docs/Model/CancelPackagesRequestData.md)
 - [CancelPackagesResponses](docs/Model/CancelPackagesResponses.md)
 - [CancelPackagesResponsesData](docs/Model/CancelPackagesResponsesData.md)
 - [ConfirmPackagesRequest](docs/Model/ConfirmPackagesRequest.md)
 - [ConfirmPackagesRequestData](docs/Model/ConfirmPackagesRequestData.md)
 - [ConfirmPackagesResponses](docs/Model/ConfirmPackagesResponses.md)
 - [ConfirmPackagesResponsesData](docs/Model/ConfirmPackagesResponsesData.md)
 - [ConsignPreferenceInfoResponses](docs/Model/ConsignPreferenceInfoResponses.md)
 - [DeletePackagesRequest](docs/Model/DeletePackagesRequest.md)
 - [DeletePackagesRequestData](docs/Model/DeletePackagesRequestData.md)
 - [DeletePackagesResponses](docs/Model/DeletePackagesResponses.md)
 - [DeletePackagesResponsesData](docs/Model/DeletePackagesResponsesData.md)
 - [DirectionsResponses](docs/Model/DirectionsResponses.md)
 - [DropoffSiteInfoResponses](docs/Model/DropoffSiteInfoResponses.md)
 - [FetchTokenResponses](docs/Model/FetchTokenResponses.md)
 - [GetActualCostRequest](docs/Model/GetActualCostRequest.md)
 - [GetActualCostRequestData](docs/Model/GetActualCostRequestData.md)
 - [GetActualCostResponses](docs/Model/GetActualCostResponses.md)
 - [GetActualCostResponsesData](docs/Model/GetActualCostResponsesData.md)
 - [GetAddressPreferenceListRequest](docs/Model/GetAddressPreferenceListRequest.md)
 - [GetAddressPreferenceListRequestData](docs/Model/GetAddressPreferenceListRequestData.md)
 - [GetAddressPreferenceListResponses](docs/Model/GetAddressPreferenceListResponses.md)
 - [GetAddressPreferenceListResponsesData](docs/Model/GetAddressPreferenceListResponsesData.md)
 - [GetConsignPreferenceListRequest](docs/Model/GetConsignPreferenceListRequest.md)
 - [GetConsignPreferenceListRequestData](docs/Model/GetConsignPreferenceListRequestData.md)
 - [GetConsignPreferenceListResponses](docs/Model/GetConsignPreferenceListResponses.md)
 - [GetConsignPreferenceListResponsesData](docs/Model/GetConsignPreferenceListResponsesData.md)
 - [GetDropoffSiteListRequest](docs/Model/GetDropoffSiteListRequest.md)
 - [GetDropoffSiteListRequestData](docs/Model/GetDropoffSiteListRequestData.md)
 - [GetDropoffSiteListResponses](docs/Model/GetDropoffSiteListResponses.md)
 - [GetDropoffSiteListResponsesData](docs/Model/GetDropoffSiteListResponsesData.md)
 - [GetHandoverSheetRequest](docs/Model/GetHandoverSheetRequest.md)
 - [GetHandoverSheetRequestData](docs/Model/GetHandoverSheetRequestData.md)
 - [GetHandoverSheetResponses](docs/Model/GetHandoverSheetResponses.md)
 - [GetHandoverSheetResponsesData](docs/Model/GetHandoverSheetResponsesData.md)
 - [GetItemPackageIdRequest](docs/Model/GetItemPackageIdRequest.md)
 - [GetItemPackageIdRequestData](docs/Model/GetItemPackageIdRequestData.md)
 - [GetItemPackageIdResponses](docs/Model/GetItemPackageIdResponses.md)
 - [GetItemPackageIdResponsesData](docs/Model/GetItemPackageIdResponsesData.md)
 - [GetLabelRequest](docs/Model/GetLabelRequest.md)
 - [GetLabelRequestData](docs/Model/GetLabelRequestData.md)
 - [GetLabelResponses](docs/Model/GetLabelResponses.md)
 - [GetLabelResponsesData](docs/Model/GetLabelResponsesData.md)
 - [GetPackageDetailRequest](docs/Model/GetPackageDetailRequest.md)
 - [GetPackageDetailRequestData](docs/Model/GetPackageDetailRequestData.md)
 - [GetPackageDetailResponses](docs/Model/GetPackageDetailResponses.md)
 - [GetPackageDetailResponsesData](docs/Model/GetPackageDetailResponsesData.md)
 - [GetPackageStatusRequest](docs/Model/GetPackageStatusRequest.md)
 - [GetPackageStatusRequestData](docs/Model/GetPackageStatusRequestData.md)
 - [GetPackageStatusResponses](docs/Model/GetPackageStatusResponses.md)
 - [GetPackageStatusResponsesData](docs/Model/GetPackageStatusResponsesData.md)
 - [GetServiceListRequest](docs/Model/GetServiceListRequest.md)
 - [GetServiceListRequestRequestData](docs/Model/GetServiceListRequestRequestData.md)
 - [GetServiceListResponses](docs/Model/GetServiceListResponses.md)
 - [GetServiceListResponsesData](docs/Model/GetServiceListResponsesData.md)
 - [GetTrackingDetailRequest](docs/Model/GetTrackingDetailRequest.md)
 - [GetTrackingDetailRequestData](docs/Model/GetTrackingDetailRequestData.md)
 - [GetTrackingDetailResponses](docs/Model/GetTrackingDetailResponses.md)
 - [GetTrackingDetailResponsesData](docs/Model/GetTrackingDetailResponsesData.md)
 - [ItemRequest](docs/Model/ItemRequest.md)
 - [ItemResponses](docs/Model/ItemResponses.md)
 - [PackageInfoRequest](docs/Model/PackageInfoRequest.md)
 - [PackageInfoWithoutServiceRequest](docs/Model/PackageInfoWithoutServiceRequest.md)
 - [PickupAddressRequest](docs/Model/PickupAddressRequest.md)
 - [PickupAddressResponses](docs/Model/PickupAddressResponses.md)
 - [RecreatePackageRequest](docs/Model/RecreatePackageRequest.md)
 - [RecreatePackageRequestData](docs/Model/RecreatePackageRequestData.md)
 - [RecreatePackageResponses](docs/Model/RecreatePackageResponses.md)
 - [RecreatePackageResponsesData](docs/Model/RecreatePackageResponsesData.md)
 - [ResponsesStatus](docs/Model/ResponsesStatus.md)
 - [ServiceInfoResponses](docs/Model/ServiceInfoResponses.md)
 - [ShipToAddressRequest](docs/Model/ShipToAddressRequest.md)
 - [ShipToAddressResponses](docs/Model/ShipToAddressResponses.md)
 - [SkuRequest](docs/Model/SkuRequest.md)
 - [SkuResponses](docs/Model/SkuResponses.md)
 - [UpdateAddressPreferenceRequest](docs/Model/UpdateAddressPreferenceRequest.md)
 - [UpdateAddressPreferenceRequestData](docs/Model/UpdateAddressPreferenceRequestData.md)
 - [UpdateAddressPreferenceResponses](docs/Model/UpdateAddressPreferenceResponses.md)
 - [UpdateAddressPreferenceResponsesData](docs/Model/UpdateAddressPreferenceResponsesData.md)
 - [UpdateConsignPreferenceRequest](docs/Model/UpdateConsignPreferenceRequest.md)
 - [UpdateConsignPreferenceRequestData](docs/Model/UpdateConsignPreferenceRequestData.md)
 - [UpdateConsignPreferenceResponses](docs/Model/UpdateConsignPreferenceResponses.md)


## Documentation For Authorization

 All endpoints do not require authorization.


## Author




"# SwaggerClient-php" 
